require "core.options"
require "core.keymaps"

require "lsp"
require "plugins"
require "help"

require "plugins.configs.alpha"
require "plugins.configs.anyjump"
require "plugins.configs.autopairs"
require "plugins.configs.autosave"
require "plugins.configs.bufferline"
require "plugins.configs.cmp"
require "plugins.configs.colorizer"
require "plugins.configs.colorscheme"
require "plugins.configs.comment"
require "plugins.configs.hop"
require "plugins.configs.indentline"
require "plugins.configs.lualine"
require "plugins.configs.luasnip"
require "plugins.configs.neoscroll"
require "plugins.configs.nvim-tree"
require "plugins.configs.telescope"
require "plugins.configs.toggleterm"
require "plugins.configs.treesitter"
require "plugins.configs.vue"
require "plugins.configs.wiki"
