local settings = {
  header = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Header",
    margin = 5,
    content = {
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣴⡶⠶⠒⠛⠛⠛⠛⠒⠶⢶⣦⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣶⠞⠋⠉⠁⣀⠀⠀⠀⣴⣶⣦⡀⣠⣴⣦⠀⠈⠉⠙⠳⣶⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
      "⠀⠀⠀⠀⠀⠀⠀⣀⣴⠟⠉⠀⣀⠀⣀⣾⣿⣷⣦⣿⣿⣿⣿⣿⣿⣿⣿⣿⢀⣀⣴⡆⠀⠉⠻⣦⣀⠀⠀⠀⠀⠀⠀⠀",
      "⠀⠀⠀⠀⠀⢠⡾⠋⠀⡀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⣤⣷⠀⠀⠙⢷⡄⠀⠀⠀⠀⠀",
      "⠀⠀⠀⢀⣴⠟⠀⠀⠀⣿⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠻⣦⡀⠀⠀⠀",
      "⠀⠀⢠⣾⠃⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⠿⣿⣟⠛⠉⢿⣿⢯⡛⠉⠛⠿⣿⣟⢿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠘⣷⡄⠀⠀",
      "⠀⠀⡾⠁⠀⠀⠀⠀⠀⣹⣿⣿⣿⡏⠀⠁⠀⠀⠀⠀⠀⠉⠁⠑⠀⠀⠀⠀⠀⠁⠙⣿⣿⣿⡇⠀⠀⠀⠀⠀⠈⢷⠀⠀",
      "⠀⣾⠃⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠘⣷⠀",
      "⢰⡟⠀⠀⠀⠀⠀⠀⠀⠈⢻⣿⡏⡀⠄⠚⠙⢄⠀⠀⠀⠀⠀⠀⠀⠀⡠⠋⡀⠓⠄⣿⣿⡗⠀⠀⠀⠀⠀⠀⠀⠀⢻⡆",
      "⢸⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡇⠀⠐⢢⡐⢌⠑⡄⠀⠀⠀⠀⢀⠎⡡⣢⠕⠉⢰⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⡇",
      "⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⡎⠈⠢⢕⡈⠂⠀⠀⠲⢁⠲⠊⠉⡆⠀⢸⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿",
      "⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠊⠃⠀⠀⡇⠰⠆⢸⣾⡀⠀⠀⢀⣿⠀⢰⠀⠀⠀⠀⠏⠒⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿",
      "⢸⡀⠀⠀⠀⠀⠀⠀⠀⡜⠀⣤⡃⠸⣭⣫⣉⡓⠾⠛⡃⠀⢀⠚⠻⢞⣋⣉⣯⠇⠸⡘⠉⢸⠀⠀⠀⠀⠀⠀⠀⠀⢠⡇",
      "⠸⣧⠀⠀⠀⠀⠀⠀⠀⢇⠀⢁⡇⠀⠉⠉⠉⠉⠉⠉⡅⠀⠈⠉⠉⠉⠉⠉⠉⠀⠀⠓⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⣼⠇",
      "⠀⢿⡄⠀⠀⠀⠀⠀⠀⠀⠈⣴⠀⠀⠀⠀⠀⠀⠀⠐⢀⠀⠀⠀⠀⡄⠀⠀⠀⠀⠀⠈⡄⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠀",
      "⠀⠀⢷⡀⠀⠀⠀⠀⠀⠀⠀⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠎⠀⠀⠀⠀⠀⠀⠀⢹⠀⠀⠀⠀⠀⠀⠀⢀⡾⠀⠀",
      "⠀⠀⠘⢿⡄⠀⠀⠀⠀⠀⢰⠀⠀⠀⠀⠀⠀⠀⢀⠤⠐⢋⡀⠸⠀⠀⠀⠀⠀⠀⠀⠀⢠⠇⠀⠀⠀⠀⠀⢠⡿⠃⠀⠀",
      "⠀⠀⠀⠈⠻⣦⠀⠀⠀⠀⠈⡀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠁⠈⠁⠆⠀⠀⠀⠀⠀⠀⢀⠞⠀⠀⠀⠀⠀⣴⠟⠁⠀⠀⠀",
      "⠀⠀⠀⠀⠀⠘⢷⣄⠀⠀⠀⠁⠠⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡤⠤⠒⠋⠀⠀⠀⠀⣠⡾⠃⠀⠀⠀⠀⠀",
      "⠀⠀⠀⠀⠀⠀⠀⠉⠻⣦⣀⠀⠀⠀⠀⠀⠁⠀⢄⠀⠀⠀⠀⠀⠀⢀⠌⠀⠀⠀⠀⠀⠀⣀⣴⠟⠉⠀⠀⠀⠀⠀⠀⠀",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⢦⣄⣀⡀⠀⠀⠀⠈⠠⠀⣀⡀⠄⠁⠀⠀⢀⣀⣠⡴⠿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠛⠻⠷⠶⠤⣤⣤⣤⣤⠤⠶⠾⠟⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
    },
    highlight = "Statement",
    default_color = "",
    oldfiles_amount = 0,
  },
  -- name which will be displayed and command
  basic = {
    type = "mapping",
    oldfiles_directory = false,
    align = "center",
    fold_section = true,
    title = "Basic Commands",
    margin = 5,
    content = {
      { "  Open current", ":ene <CR>:NvimTreeFindFileToggle<CR>", "." },
      { "  Recently used files", ":Telescope oldfiles<CR>", "r" },
      { "  Find file", ":Telescope find_files<CR>", "ff" },
      { "  Find text", ":Telescope live_grep<CR>", "t" },
      { "ﮮ  Plugins Update", ":PackerSync<CR>", "update" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },
  directory = {
    type = "mapping",
    oldfiles_directory = false,
    align = "center",
    fold_section = true,
    title = "Directory",
    margin = 5,
    content = {
      { "磌 Wiki", ":VimwikiIndex<CR>:NvimTreeFindFileToggle<CR>", "w" },
      { "  Home", ":e /home/chatlanin/README.md<CR>:NvimTreeFindFileToggle<CR>", "h" },
      { "  store/home", ":e /mnt/store/home/README.md<CR>:NvimTreeFindFileToggle<CR>", "sh" },
      { "  store", ":e /mnt/store/README.md<CR>:NvimTreeFindFileToggle<CR>", "s" },
      { "  Store.Disk", ":e /mnt/store/Store.Disk/README.md<CR>:NvimTreeFindFileToggle<CR>", "sd" },
      { "ﬓ  application", ":e /mnt/develop/application/README.md<CR>:NvimTreeFindFileToggle<CR>", "app" },
      { "  bin", ":e /mnt/develop/bin/README.md<CR>:NvimTreeFindFileToggle<CR>", "bin" },
      { "ﭱ  cpp", ":e /mnt/develop/projects/cpp/README.md<CR>:NvimTreeFindFileToggle<CR>", "cpp" },
      { "  projects", ":e /mnt/develop/projects/README.md<CR>:NvimTreeFindFileToggle<CR>", "p" },
      { "  develop", ":e /mnt/develop/README.md<CR>:NvimTreeFindFileToggle<CR>", "dev" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },
  projects = {
    type = "mapping",
    oldfiles_directory = false,
    align = "center",
    fold_section = true,
    title = "Projects",
    margin = 5,
    content = {
      { "   Nvim config", ":e /mnt/store/home/.config/nvim/init.lua<CR>:NvimTreeFindFileToggle<CR>", "conf" },
      { "冷  dwm", ":e /mnt/develop/application/dwm/dwm.6.2/config.h<CR>:NvimTreeFindFileToggle<CR>", "dwm" },
      { "冷  ftxui", ":e /mnt/develop/projects/cpp/ftxui/README.md<CR>:NvimTreeFindFileToggle<CR>", "ftxui" },
      { "冷  base", ":e /mnt/develop/projects/cpp/base/meson.build<CR>:NvimTreeFindFileToggle<CR>", "base" },
      { "冷  knowledge", ":e /mnt/develop/projects/cpp/knowledge/meson.build<CR>:NvimTreeFindFileToggle<CR>", "knowledge" },
      { "冷  rrr", ":e /mnt/develop/projects/cpp/rrr/meson.build<CR>:NvimTreeFindFileToggle<CR>", "app" },
      { "冷  (dev) emuse.v2/api", ":e /mnt/develop/projects/cpp/xaoslab/emuse.v2/api/meson.build<CR>:NvimTreeFindFileToggle<CR>", "emapi" },
      { "冷  (dev) emuse.v2/result", ":e /mnt/develop/projects/cpp/xaoslab/emuse.v2/result/meson.build<CR>:NvimTreeFindFileToggle<CR>", "emres" },
      { "冷  (dev) emuse.v2/tests", ":e /mnt/develop/projects/cpp/xaoslab/emuse.v2/tests/meson.build<CR>:NvimTreeFindFileToggle<CR>", "emtests" },
      { "冷  nvim-alpha", ":e /mnt/develop/projects/nvim/alpha-nvim/README.md<CR>:NvimTreeFindFileToggle<CR>", "alpha" },
      { "冷  tools", ":e /mnt/develop/projects/cpp/tools/meson.build<CR>:NvimTreeFindFileToggle<CR>", "tools" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },
  plugins = {
    type = "text",
    content = require("startup.functions").packer_plugins(),
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "",
    margin = 5,
    highlight = "TSString",
    default_color = "#FFFFFF",
    oldfiles_amount = 10,
  },
  footer = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Footer",
    margin = 5,
    content = { "chatlanin.com.ru" },
    highlight = "Number",
    default_color = "",
    oldfiles_amount = 0,
  },
  options = {
    mapping_keys = true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = true,
    paddings = { 1, 3, 1, 1, 5, 1 },
  },
  mappings = {
    execute_command = "<CR>",
    open_file = "o",
    open_file_split = "<c-o>",
    open_section = "<TAB>",
    open_help = "?",
  },
  colors = {
    background = "#1f2227",
    folded_section = "#56b6c2",
  },
  parts = { "header", "basic", "directory", "projects", "plugins", "footer" },
}
return settings
